REQUIRED_FAILURE_CODES = {
    "TRANSPORT_ACTOR_REJECTED", "COMMUNICATION_PR_MISMATCH", "MESSAGE_PROTOCOL_INVALID",
    "MESSAGE_ID_COLLISION", "REPLAY_TERMINAL", "CAUSATION_MISMATCH", "ROLE_TRANSITION_ILLEGAL",
    "TARGET_HEAD_STALE", "BASE_CAS_MISMATCH", "TASK_REVISION_MISMATCH", "EVIDENCE_MISSING",
    "EVIDENCE_MISMATCH", "OWNER_GATE_REQUIRED", "RECEIPT_WRITE_FAILED",
    "RECEIPT_READ_BACK_MISMATCH", "EXECUTION_START_FAILED", "EXECUTION_TIMEOUT",
    "RETRY_EXHAUSTED", "DEAD_LETTERED", "OWNER_VIEW_PERSISTENCE_FAILED",
}
