from __future__ import annotations
from typing import Protocol, Any

class GitHubPort(Protocol):
    def write_comment(self, pr_number: int, body: str) -> int: ...
    def read_comment(self, comment_id: int) -> Any: ...
    def fetch_comments(self, pr_number: int) -> list[Any]: ...
    def read_protected_file(self, path: str) -> tuple[str, str]: ...
    def fetch_pr_meta(self, pr_number: int) -> Any: ...
    def fetch_protected_main_sha(self) -> str: ...
    def fetch_task_meta(self, issue_number: int) -> Any: ...
    def fetch_evidence(self, reference: str) -> Any: ...

class RoleExecutor(Protocol):
    def start(self, role: str, message: Any) -> Any: ...
    def wait(self, execution_id: str, timeout_seconds: float) -> Any: ...
