version: '3'

tasks:
  zb:exec:lester:implement-r01:
    cmds:
      - cmd: python scripts/zb_execution_cli.py execute --from-env
        timeout: 30m

  zb:exec:duncan:qc-r01:
    cmds:
      - cmd: python scripts/zb_execution_cli.py qc --from-env
        timeout: 15m
